### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by mqchua**
Updated timer CSS, timeline pictures, button themes, and hyperlinks.

Screenshot 2020-12-10 at 3 02 47 AM
Screenshot 2020-12-10 at 2 25 51 AM

### CODE REVIEW

**Comment by Wincenttjoi** [comment]
What about the pictures?

**Comment by mqchua** [comment]
@Wincenttjoi the proposal pictures i get from where ah

**Review by thewongwayround — APPROVED** [review]
Just a question, why is the css done in index.css and not App.css?

**Comment by Wincenttjoi** [comment]
> Just a question, why is the css done in index.css and not App.css?

How can u approve before ur questions are answered hahaha so cute

**Review by Nielsencu — APPROVED** [review]

**Pull request merged**
