### PR TITLE
Reactjs repo

### PR DESCRIPTION
**Pull request by thewongwayround**
Hi, please read the commits and give feedback, thank you!

### CODE REVIEW

**Comment by Wincenttjoi** [comment]
> Hi, please read the commits and give feedback, thank you!

Remember for this section give the details of what changes you have made, as well as screenshots on the UI if necessary!

**Comment by thewongwayround** [comment]
Ah, ok
I initialised the react app with yarn create-app and deleted unnecessary default files. Then made the navbar in App.js and routing to the various pages. Do note I created components for the pages for routing. Feel free to edit them in your tasks. The navbar is also not exactly the same as in the wireframe, I am not sure how to spread all the components along the bar. On the right are buttons and the left is just a currently just a text. I also added .eslintcache to .gitignore incase it appears again. 
image

**Review by Nielsencu — APPROVED** [review]
the  App.css' contents can be removed since its not used? and in the App.js would it be better to wrap the Route components with a switch instead of a div?

**Comment by Wincenttjoi** [comment]
Great! Can just do in point form next time for the summary of the PR to ease the reading. 

I think for now its fine to merge it first so that the other 2 can start on their work, while meantime u can continue figuring out the CSS for the top toolbar to be centralized.

**Comment by Wincenttjoi** [comment]
> the App.css' contents can be removed since its not used? and in the App.js would it be better to wrap the Route components with a switch instead of a div?

There are multiple ways to do your CSS styling. You can consolidate everything in the App.css file for all the css related stuff, you can do inline css style, etc. Some way of styling of better than others, but since this is a very small project, I let you guys explore and choose as long as they are consistent throughout. You may want to check this out https://www.sitepoint.com/react-components-styling-options/

**Review by mqchua — APPROVED** [review]

**Pull request merged**
