### PR TITLE
Faqpagefix

### PR DESCRIPTION
**Pull request by Nielsencu**
Made Navbar sticky so that when in /workshop page ( not workshop detail ), people can go back to homepage without having to scorll back to top.

Page is now responsive to resizing. 
Title of workshop is now above image picture.
Separated the contents of machine learning, blockchain and external workshop.
Moved css files to styles.js.
Refactored faqpage and also workshopdetail page.
Datas are stored in data.js.

https://user-images.githubusercontent.com/50238554/102859579-189a0780-4467-11eb-84e8-9081573d0c9e.mp4

### CODE REVIEW

**Comment by Wincenttjoi** [comment]
@Nielsencu would be great if you can deconflict the files, thanks nielsen!

**Comment by thewongwayround** [comment]
there are merge conflicts with main @Nielsencu

**Comment by Nielsencu** [comment]
Deconflicted!

**Comment by Wincenttjoi** [comment]
> Deconflicted!

Hi @Nielsencu can't approve yet, there's some bugs on workshop pages. You can also proceed with the next iteration of jira tickets assigned before merging this PR

**Comment by Nielsencu** [comment]
Oh its not a bug haha I havent put in the pictures yet. Will update when all of the tickets are completed!

**Comment by Nielsencu** [comment]
Theres still a lot of white spaces in the paper component, any ideas on what to do? or do I leave it as it is
image

**Pull request merged**
