### PR TITLE
Reactjs repo

### PR DESCRIPTION
**Pull request by thewongwayround**
fixed sponsor page
large:
image
small:
image

fixed blog page
image

### CODE REVIEW

**Comment by mqchua** [comment]
Just a question, should the blog and date be flex-end?

Screenshot 2020-12-20 at 4 19 31 PM

**Comment by thewongwayround** [comment]
> Just a question, should the blog and date be flex-end?
> 
> Screenshot 2020-12-20 at 4 19 31 PM

I decided to center them after adding the background since there are colors at the corner. this is the alternative, pick your poison haha @mqchua 
image

**Comment by thewongwayround** [comment]
image
i can do it like this as well, maybe the rest can chip in with ur opinions? @mqchua @Nielsencu @Wincenttjoi

**Comment by Wincenttjoi** [comment]
> image
> i can do it like this as well. this is the most i can go b4 the words get too close to the corners. maybe the rest can chip in with their opinions? @mqchua @Nielsencu @Wincenttjoi



> image
> i can do it like this as well. this is the most i can go b4 the words get too close to the corners. maybe the rest can chip in with their opinions? @mqchua @Nielsencu @Wincenttjoi

I actually like this but ultimately ops will have the final say. May want to consider standardizing this background and title throughout the webpages if u want (pretty sure theyre fine with it)

**Comment by Nielsencu** [comment]
Add a title prop to the bottombar component so that everyone else can reuse the component

**Review by Nielsencu — APPROVED** [review]

**Pull request merged**
